# Generated by Django 4.2.24 on 2025-09-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='name',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
